version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/packages/sshnoports/tools/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/tests/end2end_tests/image/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sshnoports/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/packages/sshnp_gui/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/packages/python/sshnoports_sdk/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/packages/python/sshnpdpy/"
    schedule:
      interval: "daily"
