name: sshnoports
description: Encrypted/Secure control plane for ssh/d or other commands in the future

# NOTE: If you update the version number here, you
# must also update it in version.dart
version: 3.3.0

homepage: https://docs.atsign.com/

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies: 
  args: 2.4.2
  at_client: 3.0.61
  at_lookup: 3.0.37
  at_onboarding_cli: 1.3.0
  at_utils: 3.0.13
  crypton: 2.1.0
  dartssh2: 2.8.2
  ssh_key: ">=0.7.1 <0.9.0"
  uuid: 3.0.7
  logging: 1.2.0
  version: 3.0.2
  socket_connector: 1.0.8
  meta: ^1.9.1

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
