name: sshnoports
description: Encrypted/Secure control plane for ssh/d or other commands in the future
version: 2.0.2
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies: 
  args: ^2.3.0
  at_lookup: ^3.0.11
  at_onboarding_cli: ^1.0.0
  crypton: ^2.0.3
  dartssh2: ^2.6.0
  ssh_key: ">=0.7.1 <0.9.0"
  uuid: ^3.0.6

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
