name: sshnoports
description: Encrypted/Secure control plane for ssh/d or other commands in the future
version: 3.0.0
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies: 
  args: ^2.4.0
  at_client: ^3.0.57
  at_lookup: ^3.0.35
  at_onboarding_cli: ^1.2.5
  at_utils: ^3.0.12
  crypton: ^2.1.0
  dartssh2: ^2.8.2
  ssh_key: ">=0.7.1 <0.9.0"
  uuid: ^3.0.7
  logging: ^1.1.1
  version: ^3.0.2

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
