[tool.poetry]
name = "sshnpd"
version = "0.4.3"
description = "Python implementation of SSH No Ports daemon"
authors = ["Xavier Lin <xavier.lin@atsign.com >"]
maintainers = ["Chris Swan <chris@atsign.com>"]
readme = "README.md"
homepage = "https://github.com/atsign-foundation/noports"

[tool.poetry.scripts]
sshnpd = 'sshnpd:main'

[tool.poetry.dependencies]
python = "^3.10"
atsdk = "0.2.4"
bcrypt = "4.1.2"
cffi = "1.16.0"
cryptography = "42.0.3"
paramiko = "3.4.0"
pycparser = "2.21"
PyNaCl = "1.5.0"
setuptools = "69.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
