[tool.poetry]
name = "sshnpd"
version = "0.4.12"
description = "Python implementation of SSH No Ports daemon"
authors = ["Xavier Lin <xavier.lin@atsign.com >"]
maintainers = ["Chris Swan <chris@atsign.com>"]
readme = "README.PyPI.md"
homepage = "https://github.com/atsign-foundation/noports"

[tool.poetry.scripts]
sshnpd = 'sshnpd:main'

[tool.poetry.dependencies]
python = "^3.10"
atsdk = "0.2.23"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
