version: "3.0"
services:
  activate:
    build:
      context: ../../../ # root of the repo
      dockerfile: ./packages/sshnoports/tools/Dockerfile.activate
    volumes:
      - ${HOME}/.atsign/keys:/atsign/.atsign/keys
    command: -a "${TO}" -c "${TO_CRAM}"
  sshnpd:
    build:
      context: ../../../ # root of the repo
      dockerfile: ./packages/sshnoports/tools/Dockerfile
    volumes:
      - ${HOME}/.atsign/keys:/atsign/.atsign/keys
    command: -a "${TO}" -m "${FROM}" -d "${DEVICE}" -s -u -v
    depends_on:
      activate:
        condition: service_completed_successfully
