name: sshnoports
publish_to: none

version: 4.0.0-rc.8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core:
    git:
      url: https://github.com/atsign-foundation/sshnoports.git
      path: packages/noports_core
      ref: gkc/feat/teams-enterprise-mdp
  at_onboarding_cli: 1.4.0

dependency_overrides:
  # Pin the dependencies of noports_core
  archive: 3.3.9
  args: 2.4.2
  at_client: 3.0.68
  at_lookup: 3.0.41
  at_utils: 3.0.15
  crypton: 2.1.0
  dartssh2: 2.8.2
  logging: 1.2.0
  meta: 1.9.1
  socket_connector: 1.0.11
  ssh_key: 0.8.0
  uuid: 3.0.7
  version: 3.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.1
  build_runner: ^2.4.6
  build_version: ^2.1.1
