name: sshnoports
publish_to: none

# NOTE: If you update the version number here, you
# must also update it in version.dart
version: 4.0.0-rc.6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core: 4.0.0-dev.1
  at_onboarding_cli: 1.3.0

dependency_overrides:
  # Pin the dependencies of noports_core
  archive: 3.3.9
  args: 2.4.2
  at_client: 3.0.65
  at_lookup: 3.0.40
  at_utils: 3.0.15
  crypton: 2.1.0
  dartssh2: 2.8.2
  ssh_key: 0.8.0
  uuid: 3.0.7
  logging: 1.2.0
  version: 3.0.2
  socket_connector: 1.0.11
  meta: 1.9.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
  mocktail: ^0.3.0
